package bootstrap

import (
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/netip"
	"net/url"
	"os"
	"os/signal"
	"strconv"
	"strings"
	"syscall"
	"time"

	"github.com/gin-gonic/gin"
	apihttp "github.com/touken928/wirehub/internal/api/http"
	"github.com/touken928/wirehub/internal/config"
	"github.com/touken928/wirehub/internal/repo"
	"github.com/touken928/wirehub/internal/service"
	"github.com/touken928/wirehub/internal/static"
	"github.com/touken928/wirehub/internal/vpn/runtime"
	"github.com/touken928/wirehub/internal/vpn/tunnel"
)

func accessLogFormatter(param gin.LogFormatterParams) string {
	path := param.Request.URL.Path
	if raw := param.Request.URL.Query(); len(raw) > 0 {
		for _, key := range []string{"setup_token", "token"} {
			if _, ok := raw[key]; ok {
				raw.Set(key, "REDACTED")
			}
		}
		if encoded := raw.Encode(); encoded != "" {
			path += "?" + encoded
		}
	}
	param.Path = path

	var statusColor, methodColor, resetColor, latencyColor string
	if param.IsOutputColor() {
		statusColor = param.StatusCodeColor()
		methodColor = param.MethodColor()
		resetColor = param.ResetColor()
		latencyColor = param.LatencyColor()
	}
	return fmt.Sprintf("[GIN] %v |%s %3d %s|%s %8v %s| %15s |%s %-7s %s %#v\n%s",
		param.TimeStamp.Format("2006/01/02 - 15:04:05"), statusColor, param.StatusCode,
		resetColor, latencyColor, param.Latency, resetColor, param.ClientIP,
		methodColor, param.Method, resetColor, param.Path, param.ErrorMessage)
}

type recoveryLogWriter struct {
	inner io.Writer
}

func (w *recoveryLogWriter) Write(p []byte) (int, error) {
	lines := strings.Split(string(p), "\n")
	for i, line := range lines {
		fields := strings.SplitN(line, " ", 3)
		if len(fields) != 3 || !strings.HasPrefix(fields[2], "HTTP/") {
			continue
		}
		fields[1] = redactRequestTarget(fields[1])
		lines[i] = strings.Join(fields, " ")
	}
	return w.inner.Write([]byte(strings.Join(lines, "\n")))
}

func redactRequestTarget(target string) string {
	u, err := url.ParseRequestURI(target)
	if err != nil || u.RawQuery == "" {
		return target
	}
	query := u.Query()
	for _, key := range []string{"setup_token", "token"} {
		if _, ok := query[key]; ok {
			query.Set(key, "REDACTED")
		}
	}
	u.RawQuery = query.Encode()
	return u.RequestURI()
}

func setupURLHost(cfg *config.RuntimeConfig) string {
	if addr, err := netip.ParseAddr(cfg.Bind); err == nil && addr.IsUnspecified() {
		return "localhost:" + strconv.Itoa(cfg.Port)
	}
	return cfg.ListenAddr
}

// Run wires persistence, control plane, data plane, and HTTP serving.
// Blocks until SIGINT/SIGTERM, then performs graceful shutdown.
func Run(cfg *config.RuntimeConfig) error {
	st, err := repo.New(cfg)
	if err != nil {
		return err
	}

	app := service.NewApp(st, tunnel.GenerateKeyPair)

	configured, err := st.IsConfigured()
	if err != nil {
		return err
	}

	// Determine the setup token: generated on startup only when unconfigured.
	// It lives in memory for the lifetime of this process and becomes irrelevant
	// after successful setup.
	var setupToken string
	if !configured {
		setupToken = "" // will be generated by RegenerateSetupToken below
	}

	apiSrv := apihttp.New(app, cfg.JWTSecret, setupToken, setupURLHost(cfg))

	// Generate and log the first-run setup token when hub is unconfigured.
	// Delegates to the handler layer so the same code path covers reset too.
	if !configured {
		apiSrv.RegenerateSetupToken()
	}

	gin.SetMode(gin.ReleaseMode)
	r := gin.New()
	r.Use(gin.RecoveryWithWriter(&recoveryLogWriter{inner: os.Stdout}))
	r.Use(gin.LoggerWithFormatter(accessLogFormatter))

	stack := runtime.NewStack(cfg, runtimeCallbacks{app: app}, r)
	app.Hub.SetNetworkRuntime(stack)

	apihttp.RegisterRoutes(r, apiSrv)
	if err := static.Mount(r); err != nil {
		return err
	}

	if configured {
		bundle, err := app.LoadSyncBundle()
		if err != nil {
			return err
		}
		if err := stack.Start(bundle); err != nil {
			return err
		}
	} else {
		log.Printf("WireHub setup required — open http://%s/setup with the setup token from the log above", setupURLHost(cfg))
	}

	// Start background cleanup for the login rate limiter (idle entry eviction).
	if lim := apiSrv.LoginLimiter(); lim != nil {
		lim.StartCleanupLoop()
	}

	srv := &http.Server{
		Addr:              cfg.ListenAddr,
		Handler:           r,
		ReadHeaderTimeout: 10 * time.Second,
		ReadTimeout:       30 * time.Second,
		WriteTimeout:      60 * time.Second,
		IdleTimeout:       120 * time.Second,
	}
	// Start server in background.
	go func() {
		log.Printf("WireHub listening on %s", cfg.ListenAddr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("listen: %v", err)
		}
	}()

	// Wait for interrupt signal for graceful shutdown.
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Println("Shutting down server...")

	// Stop the login rate limiter cleanup goroutine before server shutdown.
	if lim := apiSrv.LoginLimiter(); lim != nil {
		lim.StopCleanupLoop()
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	return srv.Shutdown(ctx)
}
